sudo: required

services:
  - docker

before_install:
  - docker pull resin/rpi-raspbian

language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
before_install :
  - cd install ; ./setup.sh
script: python tests/test_installer.py
branches:
  only:
    - master