sudo: required

language: python
python:
  - "2.6"

install:
  - sudo DEBIAN_FRONTEND=noninteractive bash install/setup.sh $TRAVIS_BUILD_DIR $USER

script:
  - python tests/test_installer.py
  
branches:
  only:
    - master